### ISSUE TITLE
无法连接Azure Open AI的GPT模型

### ISSUE THREAD

**Issue by starlee822** [OpenBMB/XAgent#165]
运行python run.py --task "put your task here" --model "gpt-4"报错如下：

>openai.error.AuthenticationError: Incorrect API key provided: 87*******************bce4. You can find your API key at https://platform.openai.com/account/api-keys.

Config.yaml文件节选如下，填写了Azure OpenAI的API Key和API base，删除了orgnazation，其他内容保持不变。assets中其他config文件未修改。XAgent支持Azure OpenAI吗？有没有Azure版本的config.yaml可以参考一下。
```
api_keys:
  gpt-3.5-turbo-16k:
    - api_key: 87********************************1bce4
      api_base: https://*****.openai.azure.com/
      api_type: azure
      api_version: 2023-07-01-preview
      engine: GPT-35-Turbo-16k
    - api_key: 87********************************1bce4
      model: gpt-3.5-turbo-16k
  gpt-4:    
    - api_key: 87********************************1bce4
      model: gpt-4
    - api_key: 87********************************1bce4
      model: gpt-4
  gpt-4-32k:
    - api_key: 87********************************1bce4
      model: gpt-4-32k
    - api_key: 87********************************1bce4
      model: gpt-4-32k
```
