### ISSUE TITLE
运行docker compose up出现failed to mount local volume: mount /assets/config:/var/lib/docker/volumes/toolserverconfig/_data, flags: 0x1000: no such file or directory

### ISSUE THREAD

**Issue by BlueDarkUP** [OpenBMB/XAgent#289]
## Issue Description / 问题描述
运行docker compose up会出现 Error response from daemon: error while mounting volume '/var/lib/docker/volumes/toolserverconfig/_data': failed to mount local volume: mount /assets/config:/var/lib/docker/volumes/toolserverconfig/_data, flags: 0x1000: no such file or directory / 请详细描述您遇到的错误或问题。

## Steps to Reproduce / 复现步骤
运行 docker compose up / 请提供复现错误的具体步骤。

## Expected Behavior / 预期行为
构建并启动由 Docker Compose 文件定义的服务 / 请描述您期望的正确行为。

## Environment / 环境信息
- Windows11 / 操作系统：
- 3.10（没使用conda） / Python 版本：
- docker：4.25.2 (129061)/ 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
![屏幕截图 2023-12-02 105930](https://github.com/OpenBMB/XAgent/assets/119296966/696d7fcf-b4a5-4384-b383-295aee18abe6)

## Additional Notes / 其他备注
我会尝试使用conda构建环境

**Comment by BlueDarkUP** [comment]
好吧，我试了conda，还是有相同的问题
![屏幕截图 2023-12-02 121913](https://github.com/OpenBMB/XAgent/assets/119296966/72983bdd-16c2-4435-8a0f-604c01c7097e)

**Comment by BlueDarkUP** [comment]
我将docker-compose运行文件中的
```
volumes:
```
部分更改成
```
volumes:
  xagentmongodb:
  toolserverconfig:
    name: toolserverconfig
    driver: local
    driver_opts:
      type: none
      device: d:/xgaentllm/assets/config/
      o: bind
```
（将device改为绝对路径）
docker compose up可以成功运行了
