### ISSUE TITLE
[feature]支持自定义OPENAI_API_BASE

### ISSUE THREAD

**Issue by VectorZhao** [OpenBMB/XAgent#3]
用户可以使用第三方chatgpt服务，通过自定义API URL和API KEY来实现。

**Comment by luyaxi** [comment]
该功能已集成，请在config.yml中openai_key中添加需要的请求参数，例如  
gpt-4-32k: 
    - api_key: xxx
      api_base: xxxx
      api_type: azure
      api_version: 2023-07-01-preview
      engine: gpt4-32

**Comment by VectorZhao** [comment]
> 该功能已集成，请在config.yml中openai_key中添加需要的请求参数，例如 gpt-4-32k: - api_key: xxx api_base: xxxx api_type: azure api_version: 2023-07-01-preview engine: gpt4-32
比如我要使用自己搭建的[one-api](https://github.com/songquanpeng/one-api)的gpt3.5-16k，只需要做如下配置吧

```
openai_keys:
  gpt-3.5-turbo-16k:
    - api_key: sk-xxxxx
      api_base: https://api.xxx.xxx
      model: gpt-3.5-turbo-16k

default_completion_kwargs:
  model: gpt-3.5-turbo-16k
  temperature: 0.5
  request_timeout: 60
```
