### ISSUE TITLE
When using Azure token, I got: Must provide an 'engine' or 'deployment_id' parameter 

### ISSUE THREAD

**Issue by yinfangchen** [OpenBMB/XAgent#346]
## Issue Description / 问题描述
I got this error
```
XAgentServer.exts.exception_ext.XAgentRunningError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'>
```
## Steps to Reproduce / 复现步骤
I configure it in this way:
```
api_keys:
...
  gpt-4:    
    - api_key: 
      api_base:
      api_type: azure
      model: gpt-4
```
## Expected Behavior / 预期行为
It should work fine 

## Environment / 环境信息
- Operating System / 操作系统：MacOS
- Python Version / Python 版本：3.11
- Other Relevant Information / 其他相关信息：

## Error Screenshots 
<img width="1003" alt="Screenshot 2023-12-15 at 5 04 56 PM" src="https://github.com/OpenBMB/XAgent/assets/22325534/6e254548-e20b-4a7c-bfcd-4e1c5f5bf814">

**Comment by Umpire2018** [comment]
```yml
api_keys:
  gpt-3.5-turbo-16k:
    - api_key: sk-xxxxx
      api_base: https://example.com
      api_type: azure
      api_version: 2023-07-01-preview
      engine: GPT-35-Turbo-16k
```

Please follow azure format, refer to [here](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models).
