### ISSUE TITLE
(HTTP code 500) server error - Mounts denied: The path /assets/config is not shared from the host and is not known to Docker.

### ISSUE THREAD

**Issue by Tseian** [OpenBMB/XAgent#352]
## Issue Description / 问题描述
(HTTP code 500) server error - Mounts denied: The path /assets/config is not shared from the host and is not known to Docker. You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing. See https://docs.docker.com/desktop/mac for more info.

## Steps to Reproduce / 复现步骤
execute `docker compose up` in project root dir 

![image](https://github.com/OpenBMB/XAgent/assets/13184460/0688c02f-3398-4c51-aec0-691336f0b0f7) 
![image](https://github.com/OpenBMB/XAgent/assets/13184460/3dfa7baa-1a17-4951-a25c-baf9a913c7c3)
![image](https://github.com/OpenBMB/XAgent/assets/13184460/bf47a063-9b00-4922-9ac5-3bfa4369b5ee)

File sharing settings look good. docker recognized the ./assets/config as /assets/config ?

![image](https://github.com/OpenBMB/XAgent/assets/13184460/f3c7ebb5-e75e-4c42-a386-1b1a689105ef)

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。

## Environment / 环境信息
- Operating System / 操作系统：mac 13.4 
- Python Version / Python 版本：
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。

**Comment by Tseian** [comment]
![image](https://github.com/OpenBMB/XAgent/assets/13184460/7fc98f1a-22c5-4415-b5fc-771e59748c3e)

Add an env variable to locate current work dir or is there any other solution?
```sh
export XAGENT_WORK_DIR=$(pwd)/assets/config
docker compose up
```

**Comment by Turingforce** [comment]
# May fix: failed to mount local volume

## Address content in:[docker-compose.yml](https://github.com/OpenBMB/XAgent/blob/main/docker-compose.yml)

```bash
cd XAgent
vim docker-compose.yml
# replace DB_USERNAME: admin ; DB_PASSWORD: xagentmongodb ; DB_COLLECTION: TSM 
# replace /root/XAgent/assets/config
: wq
```

### Example showed as below：

```yml
DB_USERNAME: admin  
DB_PASSWORD: xagentmongodb  
DB_COLLECTION: TSM  
```

From `./assets/config`  to  `/root/XAgent/assets/config`

```yml
volumes:
  xagentmongodb:
  toolserverconfig:
    name: toolserverconfig
    driver: local
    driver_opts:
      type: none
      device: /root/XAgent/assets/config
      o: bind
```
