### ISSUE TITLE
怎么对接其他的openapi地址（第三方的openapi的网站，非镜像地址）？

### ISSUE THREAD

**Issue by itq5** [OpenBMB/XAgent#370]
## Issue Description / 问题描述
我在assets/config.yml中的api_base地址到其他三方项目的api地址，但是看日志还是请求的platform.openai.com网站
配置文件：
![image](https://github.com/OpenBMB/XAgent/assets/42521985/88cdc7aa-167b-4568-a684-b773943ce775)
![image](https://github.com/OpenBMB/XAgent/assets/42521985/85a97a7e-b569-4c03-930c-c19684c4a161)
日志：
![image](https://github.com/OpenBMB/XAgent/assets/42521985/d3c06291-54f6-4147-b7e6-67acb7c4572c)

**Comment by Guiquan-27** [comment]
同样的问题

**Comment by Umpire2018** [comment]
```yml
default_completion_kwargs:
  model: gpt-4-32k
  temperature: 0.2
  request_timeout: 60
  
```

此段指定了默认使用了模型 `gpt-4-32k`, 需修改此处来切换默认模型。
